### ISSUE TITLE
Build Support system

### ISSUE THREAD

**Issue by amyburness** [kartoza/africa_rangeland_watch#75]
- [x] #81
- [x] the information goes to the Django Backend (https://github.com/kartoza/africa_rangeland_watch/issues/84)
- [x] the support staff notification of the support ticket (#52 )
- [x] Notification to the user (on activities on the ticket) (#52)
